---
name: LaTeX

on: [push]

permissions: read-all

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # 4.1.0
        with:
          root_file: effective-keyboard-shortcuts-cheat-sheet.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: PDF
          path: effective-keyboard-shortcuts-cheat-sheet.tex
